plot_jarvis_errors('/Volumes/fsmresfiles/Basic_Sciences/Phys/L_MillerLab/limblab/User_folders/Aajan/Jarvis_results/points_GroundTruth.csv','/Volumes/fsmresfiles/Basic_Sciences/Phys/L_MillerLab/limblab/User_folders/Aajan/Jarvis_results/points_HybridNet.csv')

function [median_errors] = plot_jarvis_errors(path_GroundTruth, path_HybridNetPredictions)

%return variables: fig, median errors
%input variables: path_GroundTruth, path_HybridNetPredictions
% This takes the CSVs generated by Jarvis' built in analysis function and
% gives the median Euclidean distance from ground truth for each keypoint
%
% Inputs:
%   path_GroundTruth - ie '/Users/ercrg/LimbLab/data/Pop_18E3/DPZ/models/hand23_br_100_split2/Validation_Predictions_20220501-204850/points_GroundTruth.csv')
%   path_HybridNetPredictioins - ie '/Users/ercrg/LimbLab/data/Pop_18E3/DPZ/models/hand23_br_100_split2/Validation_Predictions_20220501-204850/points_HybridNet.csv')
%
% This will probably be mostly called from the scatter_jarvis_errors script
% eg

GroundTruth = readmatrix(path_GroundTruth);
HybridNetPredictions = readmatrix(path_HybridNetPredictions);

%% set up landmarks

pinky_t = [1 2 3];
pinky_d = [4 5 6];
pinky_m = [7 8 9];
pinky_p = [10 11 12];

ring_t = [13 14 15];
ring_d = [16 17 18];
ring_m = [19 20 21];
ring_p = [22 23 24];

middle_t = [25 26 27];
middle_d = [28 29 30];
middle_m = [31 32 33];
middle_p = [34 35 36];

index_t = [37 38 39];
index_d = [40 41 42];
index_m = [43 44 45];
index_p = [46 47 48];

thumb_t = [49 50 51];
thumb_d = [52 53 54];
thumb_m = [55 56 57];
thumb_p = [58 59 60];

palm = [61 62 63];
wrist_u = [64 65 66];
wrist_r = [67 68 69];

%% set up differences 

diff_pinky_t = zeros(size(GroundTruth,1), 1);
diff_pinky_d = zeros(size(GroundTruth,1), 1);
diff_pinky_m = zeros(size(GroundTruth,1), 1);
diff_pinky_p = zeros(size(GroundTruth,1), 1);

diff_ring_t = zeros(size(GroundTruth,1), 1);
diff_ring_d = zeros(size(GroundTruth,1), 1);
diff_ring_m = zeros(size(GroundTruth,1), 1);
diff_ring_p = zeros(size(GroundTruth,1), 1);

diff_middle_t = zeros(size(GroundTruth,1), 1);
diff_middle_d = zeros(size(GroundTruth,1), 1);
diff_middle_m = zeros(size(GroundTruth,1), 1);
diff_middle_p = zeros(size(GroundTruth,1), 1);

diff_index_t = zeros(size(GroundTruth,1), 1);
diff_index_d = zeros(size(GroundTruth,1), 1);
diff_index_m = zeros(size(GroundTruth,1), 1);
diff_index_p = zeros(size(GroundTruth,1), 1);

diff_thumb_t = zeros(size(GroundTruth,1), 1);
diff_thumb_d = zeros(size(GroundTruth,1), 1);
diff_thumb_m = zeros(size(GroundTruth,1), 1);
diff_thumb_p = zeros(size(GroundTruth,1), 1);

diff_palm = zeros(size(GroundTruth,1), 1);
diff_wrist_u = zeros(size(GroundTruth,1), 1);
diff_wrist_r = zeros(size(GroundTruth,1), 1);

%% get differences

for frame = 1:size(GroundTruth,1)
    diff_pinky_t(frame) = sqrt((HybridNetPredictions(frame,pinky_t(1))-GroundTruth(frame,pinky_t(1)))^2 + (HybridNetPredictions(frame,pinky_t(2))-GroundTruth(frame,pinky_t(2)))^2 + (HybridNetPredictions(frame,pinky_t(3))-GroundTruth(frame,pinky_t(3)))^2);
    diff_pinky_d(frame) = sqrt((HybridNetPredictions(frame,pinky_d(1))-GroundTruth(frame,pinky_d(1)))^2 + (HybridNetPredictions(frame,pinky_d(2))-GroundTruth(frame,pinky_d(2)))^2 + (HybridNetPredictions(frame,pinky_d(3))-GroundTruth(frame,pinky_d(3)))^2);
    diff_pinky_m(frame) = sqrt((HybridNetPredictions(frame,pinky_m(1))-GroundTruth(frame,pinky_m(1)))^2 + (HybridNetPredictions(frame,pinky_m(2))-GroundTruth(frame,pinky_m(2)))^2 + (HybridNetPredictions(frame,pinky_m(3))-GroundTruth(frame,pinky_m(3)))^2);
    diff_pinky_p(frame) = sqrt((HybridNetPredictions(frame,pinky_p(1))-GroundTruth(frame,pinky_p(1)))^2 + (HybridNetPredictions(frame,pinky_p(2))-GroundTruth(frame,pinky_p(2)))^2 + (HybridNetPredictions(frame,pinky_p(3))-GroundTruth(frame,pinky_p(3)))^2);

    diff_ring_t(frame) = sqrt((HybridNetPredictions(frame,ring_t(1))-GroundTruth(frame,ring_t(1)))^2 + (HybridNetPredictions(frame,ring_t(2))-GroundTruth(frame,ring_t(2)))^2 + (HybridNetPredictions(frame,ring_t(3))-GroundTruth(frame,ring_t(3)))^2);
    diff_ring_d(frame) = sqrt((HybridNetPredictions(frame,ring_d(1))-GroundTruth(frame,ring_d(1)))^2 + (HybridNetPredictions(frame,ring_d(2))-GroundTruth(frame,ring_d(2)))^2 + (HybridNetPredictions(frame,ring_d(3))-GroundTruth(frame,ring_d(3)))^2);
    diff_ring_m(frame) = sqrt((HybridNetPredictions(frame,ring_m(1))-GroundTruth(frame,ring_m(1)))^2 + (HybridNetPredictions(frame,ring_m(2))-GroundTruth(frame,ring_m(2)))^2 + (HybridNetPredictions(frame,ring_m(3))-GroundTruth(frame,ring_m(3)))^2);
    diff_ring_p(frame) = sqrt((HybridNetPredictions(frame,ring_p(1))-GroundTruth(frame,ring_p(1)))^2 + (HybridNetPredictions(frame,ring_p(2))-GroundTruth(frame,ring_p(2)))^2 + (HybridNetPredictions(frame,ring_p(3))-GroundTruth(frame,ring_p(3)))^2);

    diff_middle_t(frame) = sqrt((HybridNetPredictions(frame,middle_t(1))-GroundTruth(frame,middle_t(1)))^2 + (HybridNetPredictions(frame,middle_t(2))-GroundTruth(frame,middle_t(2)))^2 + (HybridNetPredictions(frame,middle_t(3))-GroundTruth(frame,middle_t(3)))^2);
    diff_middle_d(frame) = sqrt((HybridNetPredictions(frame,middle_d(1))-GroundTruth(frame,middle_d(1)))^2 + (HybridNetPredictions(frame,middle_d(2))-GroundTruth(frame,middle_d(2)))^2 + (HybridNetPredictions(frame,middle_d(3))-GroundTruth(frame,middle_d(3)))^2);
    diff_middle_m(frame) = sqrt((HybridNetPredictions(frame,middle_m(1))-GroundTruth(frame,middle_m(1)))^2 + (HybridNetPredictions(frame,middle_m(2))-GroundTruth(frame,middle_m(2)))^2 + (HybridNetPredictions(frame,middle_m(3))-GroundTruth(frame,middle_m(3)))^2);
    diff_middle_p(frame) = sqrt((HybridNetPredictions(frame,middle_p(1))-GroundTruth(frame,middle_p(1)))^2 + (HybridNetPredictions(frame,middle_p(2))-GroundTruth(frame,middle_p(2)))^2 + (HybridNetPredictions(frame,middle_p(3))-GroundTruth(frame,middle_p(3)))^2);

    diff_index_t(frame) = sqrt((HybridNetPredictions(frame,index_t(1))-GroundTruth(frame,index_t(1)))^2 + (HybridNetPredictions(frame,index_t(2))-GroundTruth(frame,index_t(2)))^2 + (HybridNetPredictions(frame,index_t(3))-GroundTruth(frame,index_t(3)))^2);
    diff_index_d(frame) = sqrt((HybridNetPredictions(frame,index_d(1))-GroundTruth(frame,index_d(1)))^2 + (HybridNetPredictions(frame,index_d(2))-GroundTruth(frame,index_d(2)))^2 + (HybridNetPredictions(frame,index_d(3))-GroundTruth(frame,index_d(3)))^2);
    diff_index_m(frame) = sqrt((HybridNetPredictions(frame,index_m(1))-GroundTruth(frame,index_m(1)))^2 + (HybridNetPredictions(frame,index_m(2))-GroundTruth(frame,index_m(2)))^2 + (HybridNetPredictions(frame,index_m(3))-GroundTruth(frame,index_m(3)))^2);
    diff_index_p(frame) = sqrt((HybridNetPredictions(frame,index_p(1))-GroundTruth(frame,index_p(1)))^2 + (HybridNetPredictions(frame,index_p(2))-GroundTruth(frame,index_p(2)))^2 + (HybridNetPredictions(frame,index_p(3))-GroundTruth(frame,index_p(3)))^2);

    diff_thumb_t(frame) = sqrt((HybridNetPredictions(frame,thumb_t(1))-GroundTruth(frame,thumb_t(1)))^2 + (HybridNetPredictions(frame,thumb_t(2))-GroundTruth(frame,thumb_t(2)))^2 + (HybridNetPredictions(frame,thumb_t(3))-GroundTruth(frame,thumb_t(3)))^2);
    diff_thumb_d(frame) = sqrt((HybridNetPredictions(frame,thumb_d(1))-GroundTruth(frame,thumb_d(1)))^2 + (HybridNetPredictions(frame,thumb_d(2))-GroundTruth(frame,thumb_d(2)))^2 + (HybridNetPredictions(frame,thumb_d(3))-GroundTruth(frame,thumb_d(3)))^2);
    diff_thumb_m(frame) = sqrt((HybridNetPredictions(frame,thumb_m(1))-GroundTruth(frame,thumb_m(1)))^2 + (HybridNetPredictions(frame,thumb_m(2))-GroundTruth(frame,thumb_m(2)))^2 + (HybridNetPredictions(frame,thumb_m(3))-GroundTruth(frame,thumb_m(3)))^2);
    diff_thumb_p(frame) = sqrt((HybridNetPredictions(frame,thumb_p(1))-GroundTruth(frame,thumb_p(1)))^2 + (HybridNetPredictions(frame,thumb_p(2))-GroundTruth(frame,thumb_p(2)))^2 + (HybridNetPredictions(frame,thumb_p(3))-GroundTruth(frame,thumb_p(3)))^2);

    diff_palm(frame) = sqrt((HybridNetPredictions(frame,palm(1))-GroundTruth(frame,palm(1)))^2 + (HybridNetPredictions(frame,palm(2))-GroundTruth(frame,palm(2)))^2 + (HybridNetPredictions(frame,palm(3))-GroundTruth(frame,palm(3)))^2);
    diff_wrist_u(frame) = sqrt((HybridNetPredictions(frame,wrist_u(1))-GroundTruth(frame,wrist_u(1)))^2 + (HybridNetPredictions(frame,wrist_u(2))-GroundTruth(frame,wrist_u(2)))^2 + (HybridNetPredictions(frame,wrist_u(3))-GroundTruth(frame,wrist_u(3)))^2);
    diff_wrist_r(frame) = sqrt((HybridNetPredictions(frame,wrist_r(1))-GroundTruth(frame,wrist_r(1)))^2 + (HybridNetPredictions(frame,wrist_r(2))-GroundTruth(frame,wrist_r(2)))^2 + (HybridNetPredictions(frame,wrist_r(3))-GroundTruth(frame,wrist_r(3)))^2);

end

all_diffs = cat(2, diff_pinky_t, diff_pinky_d, diff_pinky_m, diff_pinky_p, diff_ring_t, diff_ring_d, diff_ring_m, diff_ring_p, diff_middle_t, diff_middle_d, diff_middle_m, diff_middle_p, diff_index_t, diff_index_d, diff_index_m, diff_index_p, diff_thumb_t, diff_thumb_d, diff_thumb_m, diff_thumb_p, diff_palm, diff_wrist_u, diff_wrist_r);

median_errors = median(all_diffs, 1);

end

